// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiDemokrataPerson.Context;

#nullable disable

namespace WebApiDemokrataPerson.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiDemokrataPerson.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sueldo")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Apellido = "Perez",
                            FechaActualizacion = new DateTime(2024, 11, 8, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            FechaCreacion = new DateTime(2024, 11, 8, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1968, 10, 8),
                            Nombre = "Juan",
                            SegundoApellido = "Ortega",
                            SegundoNombre = "Manuel",
                            Sueldo = 7500000
                        },
                        new
                        {
                            UserId = 2,
                            Apellido = "Rincon",
                            FechaActualizacion = new DateTime(2024, 11, 8, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            FechaCreacion = new DateTime(2024, 11, 8, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1985, 9, 20),
                            Nombre = "Miguel",
                            SegundoApellido = "Ruiz",
                            SegundoNombre = "Angel",
                            Sueldo = 3000000
                        },
                        new
                        {
                            UserId = 3,
                            Apellido = "Sanchez",
                            FechaActualizacion = new DateTime(2024, 11, 8, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            FechaCreacion = new DateTime(2024, 11, 8, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1993, 5, 15),
                            Nombre = "Tatiana",
                            SegundoApellido = "Maldonado",
                            SegundoNombre = "Milena",
                            Sueldo = 4000000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
